config/routes.rb
Rails.application.routes.draw do
  resources :reservations
  resources :users
  resources :pharmacies
  resources :static_pages
  resources :groups, param: :code
  resources :sessions, only: %i[new create destroy sign_state]
  resources :medicines
  resources :price_lists
  resources :reservations
  scope path: 'groups/:atc_group_id' do
    resources :sub_groups, path: '/', param: :code
  end

  root 'application#index'
  match '/home', to: 'static_pages#home', via: 'get'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/signstate', to: 'sessions#sign_state', via: 'post'
  match '/change_area', to: 'pharmacies#change_area', via: 'post'
  match '/search_pharms', to: 'pharmacies#search', via: 'get'
  match '/ordering', to: 'medicines#order', via: 'post'
  match '/search_medicines', to: 'groups#search', via: 'get'
  match '/medicine_in_pharmacy', to: 'medicines#search', via: 'get'
  match '/user_reservations', to: 'reservations#index', via: 'post'
end

app/models/pharmacy.rb
class Pharmacy < ApplicationRecord
  validates :name, presence: true, length: { maximum: 25 }
  validates :address, presence: true, length: { maximum: 40 }
  validates :area, presence: true, length: { maximum: 25 }
  validates :phone, presence: true, length: { maximum: 20 }
  validates :worktime, presence: true, length: { maximum: 20 }

  has_many :priceLists, dependent: :destroy
end

app/controllers/pharmacies_controller.rb
class PharmaciesController < ApplicationController
  before_action :set_pharmacy, only: %i[:show edit update destroy]

  # GET /pharmacies
  # GET /pharmacies.json
  def index
    @pharmacies = Pharmacy.select(:id, :name, :address, :area, :phone, :worktime).order(:name)
    # SELECT id, name, address, area, phone, worktime FROM pharmacies
    # ORDER BY name
    respond_to do |format|
      format.html { render 'layouts/application' }
      format.json { render json: @pharmacies.to_json }
    end
  end

  def change_area
    area = params[:area]
    order = params[:order]
    time = params[:time]
    if area == 'Все'
      if time == 'all'
        @pharmacies = Pharmacy.select(:id, :name, :address, :phone, :worktime).where('LOWER(name) LIKE LOWER(?)', "%#{params[:name]}%").order(order)
        # SELECT id, name, address, phone, worktime FROM pharmacies
        # WHERE LOWER(name) LIKE LOWER(name_param) ORDER BY order_param
      else
        if time == 'day'
          @pharmacies = Pharmacy.select(:id, :name, :address, :phone, :worktime).where('LOWER(name) LIKE LOWER(?)', "%#{params[:name]}%").where.not(worktime: 'круглосуточно').order(order)
          # SELECT id, name, address, phone, worktime FROM pharmacies
          # WHERE LOWER(name) LIKE LOWER(name_param) AND NOT worktime = 'круглосуточно'
          # ORDER BY order_param
        else
          if time == 'allday'
            @pharmacies = Pharmacy.select(:id, :name, :address, :phone, :worktime).where('LOWER(name) LIKE LOWER(?)', "%#{params[:name]}%").where(worktime: 'круглосуточно').order(order)
            # SELECT id, name, address, phone, worktime FROM pharmacies
            # WHERE LOWER(name) LIKE LOWER(name_param) AND worktime = 'круглосуточно'
            # ORDER BY order_param
          end
        end
      end
    else
      if time == 'all'
        @pharmacies = Pharmacy.select(:id, :name, :address, :phone, :worktime).where('LOWER(name) LIKE LOWER(?)', "%#{params[:name]}%").where(area: area).order(order)
        # SELECT id, name, address, phone, worktime FROM pharmacies
        # WHERE LOWER(name) LIKE LOWER(name_param) AND area = area_param
        # ORDER BY order_param
      else
        if time == 'day'
          @pharmacies = Pharmacy.select(:id, :name, :address, :phone, :worktime).where('LOWER(name) LIKE LOWER(?)', "%#{params[:name]}%").where(area: area).where.not(worktime: 'круглосуточно')
                            .order(order)
          # SELECT id, name, address, phone, worktime FROM pharmacies
          # WHERE LOWER(name) LIKE LOWER(name_param) AND area = area_param
          # AND NOT worktime = 'круглосуточно' ORDER BY order_param
        else
          if time == 'allday'
            @pharmacies = Pharmacy.select(:id, :name, :address, :phone, :worktime).where('LOWER(name) LIKE LOWER(?)', "%#{params[:name]}%").where(area: area, worktime: 'круглосуточно').order(order)
            # SELECT id, name, address, phone, worktime FROM pharmacies
            # WHERE LOWER(name) LIKE LOWER(name_param) AND area = area_param
            # AND worktime = 'круглосуточно' ORDER BY order_param
          end
        end
      end
    end
    respond_to do |format|
      # format.html { render 'layouts/application' }
      format.json { render json: @pharmacies.to_json }
    end
  end

  def search
    respond_to do |format|
      # format.html { render 'layouts/application' }
      if !params[:search].blank?
        @searchedPharmacies = Pharmacy.select(:id, :name, :address).where('LOWER(name) LIKE LOWER(?)', "%#{params[:search]}%")
        # SELECT id, name, address FROM pharmacies
        # WHERE LOWER(name) LIKE LOWER(search_param)
      else
        @searchedPharmacies = nil
      end
        
      format.json { render json: @searchedPharmacies.to_json, callback: params[:callback] }
    end
  end

  # GET /pharmacies/1
  # GET /pharmacies/1.json
  def show
    unless @pharmacy.nil?
      respond_to do |format|
        format.html { render 'layouts/application' }
        format.json { render json: @pharmacy.to_json(only: %i[id name address phone worktime]) }
      end
    end
  end

  # GET /pharmacies/new
  def new
    @pharmacy = Pharmacy.new
    respond_to do |format|
      format.html { render 'layouts/application' }
    end
  end

  # GET /pharmacies/1/edit
  def edit
    unless @pharmacy.nil?
      respond_to do |format|
        format.html { render 'layouts/application' }
        format.json { render json: @pharmacy.to_json(only: %i[id name address area phone worktime]) }
      end
    end
  end

  # POST /pharmacies
  # POST /pharmacies.json
  def create
    @pharmacy = Pharmacy.new(pharmacy_params)
    respond_to do |format|
      if @pharmacy.save
        id = @pharmacy.id
        format.json { render json: { status: true, id: id } }
      else
        format.json { render json: { status: false, errors: @pharmacy.errors } }
      end
    end
  end

  # PATCH/PUT /pharmacies/1
  # PATCH/PUT /pharmacies/1.json
  def update
    if current_user.admin?
      respond_to do |format|
        if @pharmacy.update(pharmacy_params)
          id = @pharmacy.id
          format.json { render json: { status: true, id: id } }
        else
          format.json { render json: { status: false, errors: @pharmacy.errors } }
        end
      end
    end
  end

  # DELETE /pharmacies/1
  # DELETE /pharmacies/1.json
  def destroy
    @pharmacy.destroy if current_user.admin?
    # respond_to do |format|
    #  format.html { redirect_to pharmacies_url, notice: 'Pharmacy was successfully destroyed.' }
    #  format.json { head :no_content }
    # end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_pharmacy
      @pharmacy = Pharmacy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pharmacy_params
      params.require(:pharmacy).permit(:name, :address, :area, :phone, :worktime)
    end
end

app/helpers/pharmacies_helper.rb
module PharmaciesHelper
end

app/views/pharmacies/_form.html.erb
<%= form_for(pharmacy) do |f| %>
  <% if pharmacy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pharmacy.errors.count, "error") %> prohibited this pharmacy from being saved:</h2>

      <ul>
      <% pharmacy.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>

  <div class="field">
    <%= f.label :worktime %>
    <%= f.text_field :worktime %>
  </div>

  <div class="field">
    <%= f.label :type %>
    <%= f.text_field :type %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pharmacies/edit.html.erb
<h1>Editing Pharmacy</h1>

<%= render 'form', pharmacy: @pharmacy %>

<%= link_to 'Show', @pharmacy %> |
<%= link_to 'Back', pharmacies_path %>

app/views/pharmacies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pharmacies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Worktime</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pharmacies.each do |pharmacy| %>
      <tr>
        <td><%= pharmacy.name %></td>
        <td><%= pharmacy.address %></td>
        <td><%= pharmacy.phone %></td>
        <td><%= pharmacy.worktime %></td>
        <td><%= pharmacy.type %></td>
        <td><%= link_to 'Show', pharmacy %></td>
        <td><%= link_to 'Edit', edit_pharmacy_path(pharmacy) %></td>
        <td><%= link_to 'Destroy', pharmacy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pharmacy', new_pharmacy_path %>

app/views/pharmacies/new.html.erb
<h1>New Pharmacy</h1>

<%= render 'form', pharmacy: @pharmacy %>

<%= link_to 'Back', pharmacies_path %>

app/views/pharmacies/new1.html.erb
<h1>New Pharmacy</h1>

<%= render 'form', pharmacy: @pharmacy %>

<%= link_to 'Back', pharmacies_path %>

app/views/pharmacies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pharmacy.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @pharmacy.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @pharmacy.phone %>
</p>

<p>
  <strong>Worktime:</strong>
  <%= @pharmacy.worktime %>
</p>

<p>
  <strong>Type:</strong>
  <%= @pharmacy.type %>
</p>

<%= link_to 'Edit', edit_pharmacy_path(@pharmacy) %> |
<%= link_to 'Back', pharmacies_path %>